name: Generate Keymap SVG

on:
  push:
    paths:
      - '**.keymap'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  draw:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          pip install keymap-drawer
          sudo apt-get update
          sudo apt-get install -y jq yq

      - name: Convert keymap
        run: |
          keymap parse -z config/roBa.keymap > keymap.yaml

      - name: Clean keymap
        run: |
          yq 'del(.zmk_keyboard) | del(.keyboard)' keymap.yaml > keymap_clean.yaml

      - name: Convert layout
        run: |
          jq '{layout: {keys: .layouts.default_layout.layout}}' config/roBa.json > layout.yaml

      - name: Inject layout
        run: |
          yq -s '.[0] * {"layout": .[1].layout}' keymap_clean.yaml layout.yaml > combined.yaml

      - name: Draw
        run: |
          keymap draw combined.yaml > keymap.svg
