name: Generate Keymap SVG

on:
  push:
    paths:
      - '**.keymap'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  draw:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          pip install keymap-drawer
          sudo apt-get update
          sudo apt-get install -y jq yq

      - name: Convert keymap
        run: |
          keymap parse -z config/roBa.keymap > keymap.yaml

      - name: Convert keymap to JSON & remove zmk_keyboard
        run: |
          yq -o=json keymap.yaml | jq 'del(.. | .zmk_keyboard?) | del(.. | .keyboard?)' > keymap_clean.json

      - name: Convert layout
        run: |
          jq '{layout: {keys: .layouts.default_layout.layout}}' config/roBa.json > layout.json

      - name: Merge (Python yq方式)
        run: |
          jq -s '.[0] * {layout: .[1].layout}' keymap_clean.json layout.json > combined.json

      - name: Convert back to YAML
        run: |
          yq -y combined.json > combined.yaml

      - name: Debug combined.yaml
        run: cat combined.yaml

      - name: Draw
        run: |
          keymap draw combined.yaml > keymap.svg
